### Install Selenium

In [6]:
pip install pip==21.0.1

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\macju\anaconda3\python.exe -m pip install --upgrade pip' command.


In [7]:
import sys
!{sys.executable} -m pip install selenium

You should consider upgrading via the 'C:\Users\macju\anaconda3\python.exe -m pip install --upgrade pip' command.


### Install Rake NLTK & LancasterStemmer

In [8]:
!{sys.executable} -m pip install rake_nltk
from rake_nltk import Rake
from nltk.stem import LancasterStemmer

You should consider upgrading via the 'C:\Users\macju\anaconda3\python.exe -m pip install --upgrade pip' command.


### Install tabPy

In [9]:
!{sys.executable} -m pip install tabpy_client
import tabpy_client as tc

You should consider upgrading via the 'C:\Users\macju\anaconda3\python.exe -m pip install --upgrade pip' command.


### Import libraries

In [10]:
from random import randint
import time

import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

### Set up Chromedriver

In [11]:
from selenium import webdriver

#Path to ChromeDriver
PATH = "C:\Program Files (x86)\chromedriver"

#ChromeDriver Options
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--window-size=1920,1080")

#Loads useful information for web crawling and skip those are only valuable for human beings; speeds crawling
prefs = {"profile.managed_default_content_settings.images":2,
     "profile.default_content_setting_values.notifications":2,
     "profile.managed_default_content_settings.stylesheets":2,
     "profile.managed_default_content_settings.cookies":2,
     "profile.managed_default_content_settings.javascript":1,
     "profile.managed_default_content_settings.plugins":1,
     "profile.managed_default_content_settings.popups":2,
     "profile.managed_default_content_settings.geolocation":2,
     "profile.managed_default_content_settings.media_stream":2,
     }

chrome_options.add_experimental_option("prefs", prefs)
driver = webdriver.Chrome(PATH, options=chrome_options)

## Data Collection

### Get all wikipedia links to each drama

In [12]:
driver.get('https://en.wikipedia.org/wiki/List_of_South_Korean_dramas')
elems = driver.find_elements_by_class_name("div-col")

In [13]:
drama_links = []
for elem in elems:
    links = elem.find_elements_by_css_selector("a[href]")
    for link in links:
        drama_links.append(link.get_attribute("href"))

### First 5 drama links

In [14]:
print(drama_links[0:5])

['https://en.wikipedia.org/wiki/100_Days_My_Prince', 'https://en.wikipedia.org/w/index.php?title=100%25_Era&action=edit&redlink=1', 'https://en.wikipedia.org/w/index.php?title=109_Strange_Things&action=edit&redlink=1', 'https://en.wikipedia.org/wiki/12_Signs_of_Love', 'https://en.wikipedia.org/wiki/12_Years_Promise']


### Extracting the title, cast, directors, genres from wikipedia links

In [15]:
title = []
cast = []
directors = []
genres = []

for link in drama_links:
    driver.get(link)
    
    # title
    try:
        post = driver.find_elements_by_id("firstHeading")
        for elem in post:
            title.append(elem.text)
    except:
        title.append("No Title Listed")
        
    # cast
    try:
        post = driver.find_elements_by_class_name("attendee")
        cast.append(post[1].text)
    except:
        cast.append("No Actor Listed")
        
    # directors
    try:
        post = driver.find_elements_by_class_name("attendee")
        directors.append(post[0].text)
    except:
        directors.append("No Director Listed")
    
    # genres
    try:
        post = driver.find_elements_by_class_name("category")
        genres.append(post[0].text)
    except:
        genres.append("No Genre Listed")

### Crawling the imdb links

In [16]:
imdb_links = []

search_string = title

for elem in search_string:
    website = "https://search.yahoo.com/search?p=" + elem + " imdb" + "&fr=yfp-t-s&ei=UTF-8&fp=" + str(1) 
    time.sleep(randint(1, 5))
    driver.get(website)
    try:
        test = driver.find_elements_by_class_name("imdb")
        want = test[0].find_element_by_css_selector("a[href]")
        imdb_links.append(want.get_attribute("href"))
    except:
        imdb_links.append("No Plot Listed")
        
imdb_links

['http://www.imdb.com/title/tt8199972',
 'No Plot Listed',
 'http://www.imdb.com/title/tt9014802',
 'http://www.imdb.com/title/tt2585230',
 'http://www.imdb.com/title/tt5476252',
 'http://www.imdb.com/title/tt0094593',
 'No Plot Listed',
 'No Plot Listed',
 'http://www.imdb.com/title/tt10145322',
 'No Plot Listed',
 'No Plot Listed',
 'http://www.imdb.com/title/tt12015466',
 'No Plot Listed',
 'http://www.imdb.com/title/tt4449190',
 'No Plot Listed',
 'http://www.imdb.com/title/tt7654144',
 'No Plot Listed',
 'No Plot Listed',
 'http://www.imdb.com/title/tt6353134',
 'http://www.imdb.com/title/tt3061226',
 'No Plot Listed',
 'http://www.imdb.com/title/tt6954654',
 'http://www.imdb.com/title/tt0977891',
 'http://www.imdb.com/title/tt5764360',
 'No Plot Listed',
 'No Plot Listed',
 'http://www.imdb.com/title/tt4950552',
 'No Plot Listed',
 'http://www.imdb.com/title/tt2362760',
 'No Plot Listed',
 'No Plot Listed',
 'No Plot Listed',
 'No Plot Listed',
 'http://www.imdb.com/title/tt56795

In [24]:
plot = []

for link in imdb_links[0:10]:
    if (link == "No Plot Listed"):
        plot.append("No Plot Listed")
    else:
        driver.get(link)
        driver.find_element_by_class_name(presentation)
        

plot

NameError: name 'presentation' is not defined

In [19]:
plot = []

for link in imdb_links:
    if (link == "No Plot Listed"):
        plot.append("No Plot Listed")
    else:
        driver.get(link)
        test = driver.find_element_by_class_name("ipc-html-content ipc-html-content--base")
        plot.append(test.text)

plot

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".ipc-html-content ipc-html-content--base"}
  (Session info: chrome=91.0.4472.77)


### Creating the dataframe

In [12]:
init_df = pd.DataFrame(list(zip(title, genres, cast, directors, plot)), 
                       columns=['title', 'genres', "actors", "directors", "plot"])
df = init_df.copy()
df.head()

NameError: name 'plot' is not defined

In [28]:
df.shape

(1543, 5)

### Focusing on dramas with information

In [64]:
dramas = df[(df['plot'] != "No Plot Listed") & (df['plot'] != "Add a Plot »") & 
            (df['actors'] != "No Actor Listed") & (df['directors'] != "No Director Listed") & 
            (df['genres'] != "No Genre Listed")].copy()

dramas['plot'] = dramas['plot'].str.lower().str.replace('-', ' ')

dramas.reset_index(drop=True, inplace=True)
dramas.head()

title                         genres  \
0    100 Days My Prince    Historical\nRomantic comedy   
1      12 Years Promise        Romantic comedy\nFamily   
2              18 Again  Drama\nFantasy\nComing-of-age   
3  365: Repeat the Year               Mystery\nFantasy   
4               49 Days    Romance\nFantasy\nBody swap   

                                              actors  \
0  Do Kyung-soo\nNam Ji-hyun\nJo Sung-ha\nJo Han-...   
1  Lee So-yeon\nNamkoong Min\nLee Tae-im\nYoon So...   
2           Kim Ha-neul\nYoon Sang-hyun\nLee Do-hyun   
3  Lee Joon-hyuk\nNam Ji-hyun\nKim Ji-soo\nYang D...   
4  Lee Yo-won\nNam Gyu-ri\nJung Il-woo\nJo Hyun-j...   

                    directors  \
0  Lee Jong-jae\nNam Sung-woo   
1  Kim Do-hyung\nYoon Jae-won   
2               Ha Byung-hoon   
3               Kim Kyung-hee   
4              Jo Young-kwang   

                                                plot  
0  lee yul falls off a cliff and nearly dies in a...  
1  a pregnant teen is forced by her family to lea...  
2  a 37 year old man on the verge of being divorc...  
3  a story where ten people get the chance to go ...  
4  the same nightmare troubles daniel every night...

In [65]:
dramas.shape

(657, 5)

## Data Cleaning

In [66]:
dramas['title'] = dramas['title'].replace(' \(.*\)$', '', regex=True)
dramas['genres'] = dramas['genres'].replace('\\n', ', ', regex=True).replace('\[\d\]', '', regex=True).map(lambda x: x.lower().split(',')[:3])
dramas['actors'] = dramas['actors'].replace('\\n', ', ', regex=True).map(lambda x: x.split(',')[:3])
dramas['directors'] = dramas['directors'].replace('\\n', ', ', regex=True).map(lambda x: x.split(',')[:3])

dramas.head()

title                             genres  \
0    100 Days My Prince     [historical,  romantic comedy]   
1      12 Years Promise         [romantic comedy,  family]   
2              18 Again  [drama,  fantasy,  coming-of-age]   
3  365: Repeat the Year                [mystery,  fantasy]   
4               49 Days    [romance,  fantasy,  body swap]   

                                         actors  \
0     [Do Kyung-soo,  Nam Ji-hyun,  Jo Sung-ha]   
1     [Lee So-yeon,  Namkoong Min,  Lee Tae-im]   
2  [Kim Ha-neul,  Yoon Sang-hyun,  Lee Do-hyun]   
3    [Lee Joon-hyuk,  Nam Ji-hyun,  Kim Ji-soo]   
4       [Lee Yo-won,  Nam Gyu-ri,  Jung Il-woo]   

                       directors  \
0  [Lee Jong-jae,  Nam Sung-woo]   
1  [Kim Do-hyung,  Yoon Jae-won]   
2                [Ha Byung-hoon]   
3                [Kim Kyung-hee]   
4               [Jo Young-kwang]   

                                                plot  
0  lee yul falls off a cliff and nearly dies in a...  
1  a pregnant teen is forced by her family to lea...  
2  a 37 year old man on the verge of being divorc...  
3  a story where ten people get the chance to go ...  
4  the same nightmare troubles daniel every night...

In [67]:
for index, row in dramas.iterrows():
    dramas.at[index, 'actors'] = [x.lower().replace(' ', '').replace('-', '') for x in row['actors']]
    dramas.at[index, 'directors'] = [y.lower().replace(' ', '').replace('-', '') for y in row['directors']]
    dramas.at[index, 'genres'] = [z.replace(' ', '').replace('-', '').replace('-', '') for z in row['genres']]

dramas.head()

title                         genres  \
0    100 Days My Prince   [historical, romanticcomedy]   
1      12 Years Promise       [romanticcomedy, family]   
2              18 Again  [drama, fantasy, comingofage]   
3  365: Repeat the Year             [mystery, fantasy]   
4               49 Days   [romance, fantasy, bodyswap]   

                                 actors                 directors  \
0     [dokyungsoo, namjihyun, josungha]  [leejongjae, namsungwoo]   
1    [leesoyeon, namkoongmin, leetaeim]  [kimdohyung, yoonjaewon]   
2  [kimhaneul, yoonsanghyun, leedohyun]             [habyunghoon]   
3    [leejoonhyuk, namjihyun, kimjisoo]             [kimkyunghee]   
4       [leeyowon, namgyuri, jungilwoo]            [joyoungkwang]   

                                                plot  
0  lee yul falls off a cliff and nearly dies in a...  
1  a pregnant teen is forced by her family to lea...  
2  a 37 year old man on the verge of being divorc...  
3  a story where ten people get the chance to go ...  
4  the same nightmare troubles daniel every night...

## Content-based filtering using plot only

In [68]:
plot_df = dramas.copy()
plot_df.head()

title                         genres  \
0    100 Days My Prince   [historical, romanticcomedy]   
1      12 Years Promise       [romanticcomedy, family]   
2              18 Again  [drama, fantasy, comingofage]   
3  365: Repeat the Year             [mystery, fantasy]   
4               49 Days   [romance, fantasy, bodyswap]   

                                 actors                 directors  \
0     [dokyungsoo, namjihyun, josungha]  [leejongjae, namsungwoo]   
1    [leesoyeon, namkoongmin, leetaeim]  [kimdohyung, yoonjaewon]   
2  [kimhaneul, yoonsanghyun, leedohyun]             [habyunghoon]   
3    [leejoonhyuk, namjihyun, kimjisoo]             [kimkyunghee]   
4       [leeyowon, namgyuri, jungilwoo]            [joyoungkwang]   

                                                plot  
0  lee yul falls off a cliff and nearly dies in a...  
1  a pregnant teen is forced by her family to lea...  
2  a 37 year old man on the verge of being divorc...  
3  a story where ten people get the chance to go ...  
4  the same nightmare troubles daniel every night...

In [69]:
tfidf = TfidfVectorizer(stop_words='english')
tm = tfidf.fit_transform(plot_df["plot"])
tm.shape

(657, 3588)

In [70]:
cs = cosine_similarity(tm)
cs

array([[1.        , 0.02964364, 0.04906308, ..., 0.0260546 , 0.        ,
        0.03255806],
       [0.02964364, 1.        , 0.06215424, ..., 0.03300657, 0.        ,
        0.        ],
       [0.04906308, 0.06215424, 1.        , ..., 0.05462904, 0.05860424,
        0.06217818],
       ...,
       [0.0260546 , 0.03300657, 0.05462904, ..., 1.        , 0.03619124,
        0.        ],
       [0.        , 0.        , 0.05860424, ..., 0.03619124, 1.        ,
        0.        ],
       [0.03255806, 0.        , 0.06217818, ..., 0.        , 0.        ,
        1.        ]])

In [71]:
indices = pd.Series(plot_df.index, index=plot_df['title']).drop_duplicates()

def get_recommendations(title, cosine_sim=cs):
    recommended_dramas = []
    
    idx = indices[title]

    sim_scores = pd.Series(cosine_sim[idx]).sort_values(ascending=False)

    top_10_indexes = list(sim_scores.iloc[1:11].index)
    
    plot_df.set_index("title", inplace=True)
    
    for i in top_10_indexes:
        recommended_dramas.append(list(plot_df.index)[i])
    return recommended_dramas

In [72]:
get_recommendations("Crash Landing on You")

['Doctor Stranger',
 'Descendants of the Sun',
 'The King 2 Hearts',
 'Korean Peninsula',
 'Basketball',
 'Hotel King',
 'Should We Kiss First?',
 'Legend of the Blue Sea',
 'Local Hero',
 'High Society']

## Cotent-based filtering using directors, actors, genre, keywords

### Extracting keywords from plot description

In [51]:
# Make new column
dramas['keywords'] = ""

for index, row in dramas.iterrows():
    plot = row['plot']
    r = Rake()
    r.extract_keywords_from_text(plot)
    key_words_dict_scores = r.get_word_degrees()
    row['keywords'] = list(key_words_dict_scores.keys())
    
dramas_df = dramas.drop(columns = ['plot'])

In [52]:
ps = LancasterStemmer()

for i in range(dramas_df.shape[0]):
    result = []
    for word in dramas_df["keywords"][i]:
        result.append(ps.stem(word))
    dramas_df["keywords"][i] = result
    
dramas_df.set_index("title", inplace=True)

dramas_df.head()

genres  \
title                                                 
100 Days My Prince     [historical, romanticcomedy]   
12 Years Promise           [romanticcomedy, family]   
18 Again              [drama, fantasy, comingofage]   
365: Repeat the Year             [mystery, fantasy]   
49 Days                [romance, fantasy, bodyswap]   

                                                    actors  \
title                                                        
100 Days My Prince       [dokyungsoo, namjihyun, josungha]   
12 Years Promise        [leesoyeon, namkoongmin, leetaeim]   
18 Again              [kimhaneul, yoonsanghyun, leedohyun]   
365: Repeat the Year    [leejoonhyuk, namjihyun, kimjisoo]   
49 Days                    [leeyowon, namgyuri, jungilwoo]   

                                     directors  \
title                                            
100 Days My Prince    [leejongjae, namsungwoo]   
12 Years Promise      [kimdohyung, yoonjaewon]   
18 Again                         [habyunghoon]   
365: Repeat the Year             [kimkyunghee]   
49 Days                         [joyoungkwang]   

                                                               keywords  
title                                                                    
100 Days My Prince    [near, die, wand, first, detect, ag, head, att...  
12 Years Promise      [famy, new, id, kore, 12, year, lat, assum, co...  
18 Again              [new, lif, get, clos, 37, year, old, man, star...  
365: Repeat the Year  [tim, unexpect, mystery, situ, start, story, f...  
49 Days               [arm, young, lady, on, red, dress, continu, ap...

## Bag of Words Model

In [53]:
dramas_df["bag_of_words"] = ""
columns = dramas_df.columns
for index, row in dramas_df.iterrows():
    words = ""
    for col in columns:
        words = words + ' '.join(row[col]) + ' '
    row['bag_of_words'] = words
    
dramas_df.drop(columns = [col for col in dramas_df.columns if col != "bag_of_words"], inplace=True)

dramas_df.head()

bag_of_words
title                                                                  
100 Days My Prince    historical romanticcomedy dokyungsoo namjihyun...
12 Years Promise      romanticcomedy family leesoyeon namkoongmin le...
18 Again              drama fantasy comingofage kimhaneul yoonsanghy...
365: Repeat the Year  mystery fantasy leejoonhyuk namjihyun kimjisoo...
49 Days               romance fantasy bodyswap leeyowon namgyuri jun...

In [78]:
#Convert the text into a matrix of token counts
c = CountVectorizer(stop_words='english')
cm = c.fit_transform(dramas_df['bag_of_words'])
cm.shape

(657, 3830)

In [79]:
# Get the cosine similarity matrix from the count matrix
cs = cosine_similarity(cm)

# Print cosine similarty matrix
print(cs)

[[1.         0.07490059 0.070447   ... 0.06670373 0.         0.03919309]
 [0.07490059 1.         0.08178608 ... 0.07744031 0.         0.04550158]
 [0.070447   0.08178608 1.         ... 0.0728357  0.06827887 0.0855921 ]
 ...
 [0.06670373 0.07744031 0.0728357  ... 1.         0.06465082 0.08104409]
 [0.         0.         0.06827887 ... 0.06465082 1.         0.        ]
 [0.03919309 0.04550158 0.0855921  ... 0.08104409 0.         1.        ]]


In [80]:
#Shape of cs matrix
cs.shape

(657, 657)

In [81]:
indices = pd.Series(dramas_df.index).drop_duplicates()

def recommendation(title, cosine_sim = cs):
    recommended_dramas = []
    
    idx = indices[indices == title].index[0]
    
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending=False)
    
    top_10_indexes = list(score_series.iloc[1:11].index)
    
    for i in top_10_indexes:
        recommended_dramas.append(list(dramas_df.index)[i])
    return recommended_dramas

In [82]:
recommendation("Crash Landing on You")

['Alone in Love',
 'Beautiful Love, Wonderful Life',
 'Love Alert',
 'Love in the Moonlight',
 'My First Love',
 'The Third Charm',
 'Descendants of the Sun',
 'Six Flying Dragons',
 'All About My Romance',
 'I Have a Lover']

### tabPy Dashboard

In [92]:
connection = tc.Client('http://localhost:9004/')
connection.deploy('recommendation', recommendation, 'Returns list of recommended movies', override=True)

In [93]:
connection.get_endpoints()['recommend']['schema']

In [94]:
connection.query('recommendation', "Crash Landing on You")

{'response': ['Alone in Love',
  'Beautiful Love, Wonderful Life',
  'Love Alert',
  'Love in the Moonlight',
  'My First Love',
  'The Third Charm',
  'Descendants of the Sun',
  'Six Flying Dragons',
  'All About My Romance',
  'I Have a Lover'],
 'version': 1,
 'model': 'recommendation',
 'uuid': 'd084f20c-792b-4a30-bf01-952d8f29f383'}